"""add_is_archived_to_requests

Revision ID: bd061b77da2a
Revises: add_request_type
Create Date: 2026-06-16 13:19:12.061068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd061b77da2a'
down_revision: Union[str, None] = 'add_request_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'is_archived')
    # ### end Alembic commands ###
